-- Ernesto v14.4 — dossier memory + answer feedback
-- Apply in Supabase SQL Editor before relying on cross-device memory/feedback analytics.

create table if not exists public.ernesto_dossier_memory (
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id text not null,
  title text not null default 'Dossier général',
  objective text not null default '',
  summary text not null default '',
  facts jsonb not null default '[]'::jsonb,
  open_questions jsonb not null default '[]'::jsonb,
  turn_count integer not null default 0 check (turn_count >= 0),
  summarized_turn_count integer not null default 0 check (summarized_turn_count >= 0),
  last_chat_hash text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, project_id)
);

create index if not exists ernesto_dossier_memory_user_updated_idx
  on public.ernesto_dossier_memory (user_id, updated_at desc);

alter table public.ernesto_dossier_memory enable row level security;

drop policy if exists "dossier memory select own" on public.ernesto_dossier_memory;
create policy "dossier memory select own"
  on public.ernesto_dossier_memory for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "dossier memory insert own" on public.ernesto_dossier_memory;
create policy "dossier memory insert own"
  on public.ernesto_dossier_memory for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "dossier memory update own" on public.ernesto_dossier_memory;
create policy "dossier memory update own"
  on public.ernesto_dossier_memory for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "dossier memory delete own" on public.ernesto_dossier_memory;
create policy "dossier memory delete own"
  on public.ernesto_dossier_memory for delete
  to authenticated
  using (auth.uid() = user_id);

grant select, insert, update, delete on public.ernesto_dossier_memory to authenticated;
grant all on public.ernesto_dossier_memory to service_role;

create table if not exists public.ernesto_answer_feedback (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_id text,
  project_title text,
  question text,
  answer text not null,
  mode text check (mode is null or mode in ('ACTION', 'ANALYSE')),
  rating smallint not null check (rating in (-1, 1)),
  reason text check (reason is null or reason in ('too_vague', 'incorrect', 'not_practical', 'other')),
  rag_used integer,
  created_at timestamptz not null default now()
);

create index if not exists ernesto_answer_feedback_user_created_idx
  on public.ernesto_answer_feedback (user_id, created_at desc);
create index if not exists ernesto_answer_feedback_rating_created_idx
  on public.ernesto_answer_feedback (rating, created_at desc);

alter table public.ernesto_answer_feedback enable row level security;

drop policy if exists "answer feedback select own" on public.ernesto_answer_feedback;
create policy "answer feedback select own"
  on public.ernesto_answer_feedback for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "answer feedback insert own" on public.ernesto_answer_feedback;
create policy "answer feedback insert own"
  on public.ernesto_answer_feedback for insert
  to authenticated
  with check (auth.uid() = user_id);

grant select, insert on public.ernesto_answer_feedback to authenticated;
grant all on public.ernesto_answer_feedback to service_role;
grant usage, select on sequence public.ernesto_answer_feedback_id_seq to authenticated, service_role;
